### ISSUE TITLE
请问程序的具体文件目录是什么？

### ISSUE THREAD

**Issue by fly5756** [techoner/tadmin#10]
请问程序的具体文件目录是什么？包含Thinkphp的

注：发现数据导入时表格式不对，生成一半数据库，请查看一下；
INSERT INTO `configs` VALUES ('1', '站点名称', 'text', 'title', 'Tadmin - 基于ThinkPHP5.1+和AmazeUI的快速后台开发框架', 'site', '站点名称', '1', '2019-01-01 11:58:26', '2019-01-01 14:35:10');

**Comment by leeqvip** [comment]
生成数据库，采用的是thinkphp的数据迁移工具https://www.kancloud.cn/manual/thinkphp5_1/354133：
```
php think tadmin:migrate:run
```
演示站：https://github.com/techoner/tadmin-skeleton

`Tadmin`是一个扩展包，composer安装后再vendor目录里，并不会在tp项目里产生任何文件。

你是哪一步报错，报什么错，具体一些？

**Comment by supqsg** [comment]
想问下一我后台已经部署好了，想要前台效果应该怎么操作

**Comment by leeqvip** [comment]
`Tadmin` 提供了较为完善的后台，不带前台
前台毕竟是面向客户层面的。
可以看演示站的源码可以直接clone：https://github.com/techoner/tadmin-skeleton

**Comment by supqsg** [comment]
> `Tadmin` 提供了较为完善的后台，不带前台
> 前台毕竟是面向客户层面的。
> 可以看演示站的源码可以直接clone：https://github.com/techoner/tadmin-skeleton

明白，谢谢
