### ISSUE TITLE
请问支持tp6吗？

### ISSUE THREAD

**Issue by linwoodf33** [techoner/tadmin#13]
看您代码里有支持tp6的，我用composer create-project topthink/think tp 新装了tp6.0.5
cd到tp目录下执行 composer require techone/tadmin出了个问题，是不支持tp6.0.5吗？
报错如下：
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - topthink/think-captcha[v2.0, ..., v2.0.1] require topthink/framework 5.1.x-dev -> found topthink/framework[5.1.x-dev] but it does not match your minimum-stability.
    - topthink/think-captcha v2.0.2 requires topthink/framework 5.1.* -> found topthink/framework[v5.1.0, ..., v5.1.40] but it conflicts with your root composer.json require (^6.0.0).
    - techone/tadmin v0.6.2 requires topthink/think-captcha ^2.0 -> satisfiable by topthink/think-captcha[v2.0, v2.0.1, v2.0.2].
    - Root composer.json requires techone/tadmin ^0.6.2 -> satisfiable by techone/tadmin[v0.6.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by leeqvip** [comment]
代码更新了tp6，尚未完成测试工作，所以还没有正式发布

**Comment by hsluoyz** [comment]
@techoner

**Comment by Aido21** [comment]
Hi,
my casbin is the last stable version 2.3.0 but 

  Problem 1
    - casbin/think-adapter[v1.0.0, ..., v1.0.1] require casbin/casbin 1.* -> found casbin/casbin[v1.0.0, v1.0.1, v1.0.2, v1.0.3] but it conflicts with your root composer.json require (2.3.0).
    - casbin/think-adapter[v1.0.2, ..., v1.0.3] require casbin/casbin ^1.0 -> found casbin/casbin[v1.0.0, v1.0.1, v1.0.2, v1.0.3] but it conflicts with your root composer.json require (2.3.0).
    - techone/tadmin v0.6.2 requires casbin/think-adapter ~1.0 -> satisfiable by casbin/think-adapter[v1.0.0, v1.0.1, v1.0.2, v1.0.3].
    - Root composer.json requires techone/tadmin ^0.6.2 -> satisfiable by techone/tadmin[v0.6.2].

**Comment by hsluoyz** [comment]
@techoner

**Comment by leeqvip** [comment]
现已支持ThinkPHP6.0 ！
