### ISSUE TITLE
Dependencies issue

### ISSUE THREAD

**Issue by Aido21** [techoner/tadmin#14]
Hi,
my casbin is the last stable version 2.3.0 but

Problem 1
- casbin/think-adapter[v1.0.0, ..., v1.0.1] require casbin/casbin 1.* -> found casbin/casbin[v1.0.0, v1.0.1, v1.0.2, v1.0.3] but it conflicts with your root composer.json require (2.3.0).
- casbin/think-adapter[v1.0.2, ..., v1.0.3] require casbin/casbin ^1.0 -> found casbin/casbin[v1.0.0, v1.0.1, v1.0.2, v1.0.3] but it conflicts with your root composer.json require (2.3.0).
- techone/tadmin v0.6.2 requires casbin/think-adapter ~1.0 -> satisfiable by casbin/think-adapter[v1.0.0, v1.0.1, v1.0.2, v1.0.3].
- Root composer.json requires techone/tadmin ^0.6.2 -> satisfiable by techone/tadmin[v0.6.2].

**Comment by hsluoyz** [comment]
@techoner

**Comment by basakest** [comment]
In the composer.json file of think-adapter, there is one line about the version of casbin/casbin : "casbin/casbin": "^1.0". This means that think-adapter require the version of casbin/casbin greater than 1.0.0 and less than 2.0.0. You can enter composer require "casbin/casbin:^1.0" in your terminal to meet this demand. But this may cause another dependencies issue about symfony/expression-language. So you can enter composer require "casbin/casbin:^1.0" "symfony/expression-language ^3.4|^4.0" to meet both needs at once.

**Comment by hsluoyz** [comment]
@Aido21

**Comment by hsluoyz** [comment]
Marked as resolved.
