### ISSUE TITLE
Could not open input file: think

### ISSUE THREAD

**Issue by zengpuzhang** [techoner/tadmin#3]
> git clone https://github.com/techoner/tadmin.git
> composer install 

{11:20}/webroot/tadmin:master ✗ ➭ ls -ah
.              .git           .gitignore     LICENSE        composer.json  config         helper.php     route          vendor
..             .gitattributes .styleci.yml   README.md      composer.lock  database       resource       src
{11:20}/webroot/tadmin:master ✗ ➭ php think tadmin:init

**Could not open input file: think**
{11:20}/webroot/tadmin:master ✗ ➭

**Comment by leeqvip** [comment]
You must install via composer，First install the thinkphp project
```
composer create-project topthink/think tp
```
Then in your tp project, install the tadmin:
```
composer require techone/tadmin
```
