### ISSUE TITLE
希望出一个基于RESTful的例子

### ISSUE THREAD

**Issue by xzusoft** [techoner/tadmin#6]
希望出一个ThinkPHP5.1使用 RESTful 方式，think-casbin权限管理的demo。看了很久的文档，还是不太明白。官方的文档写的入门门槛有点高

**Comment by leeqvip** [comment]
你问的这个不属于Tadmin的范畴，只是Tadmin在权限验证上使用了Casbin基础功能。

关于Casbin的目前只有官方仓库，以及官方文档，基本都是基于Go的，php的介绍比较少，你也可以进Casbin官方QQ群。

**Comment by xzusoft** [comment]
恩
