### ISSUE TITLE
请教如何处理？

### ISSUE THREAD

**Issue by fly5756** [techoner/tadmin#8]
ThinkPHP5.1安装正常后，执行“composer require techone/tadmin”出现错误提示：
using version ^0.6.0 for techone/tadmin
./composer.json has been updated
root package ' techone/tadmin' cannot require itself in its composer.json did you accidentally name your root package after an external package?
请问这是什么原因？

我是个新手，请问能发布一个详细的教程变于学习吗？

**Comment by leeqvip** [comment]
@fly5756 你应该是先`git clone`了，然后又`composer require`，所有提示重复了。
### 安装步骤：
#### 创建thinkphp项目（**如果没有**）：
```
composer create-project topthink/think tp
```
#### 在ThinkPHP项目里，安装Tadmin扩展：
```
composer require techone/tadmin
```
#### 初始化和数据迁移(**确保数据库连接信息配置正确**)
```
php think tadmin:init
php think tadmin:migrate:run
```
#### 配置
添加行为在 `application/tags.php`
```
return [

    'app_init'     => [
        \tadmin\behavior\Boot::class,
    ],

    // ...
];
```
