### ISSUE TITLE
php think tadmin:migrate:run

### ISSUE THREAD

**Issue by fly5756** [techoner/tadmin#9]
InvalidArgumentException
there was a problem connecting to the database:sqlstate[hy000] [2006] mysql server has gone away

**Comment by leeqvip** [comment]
检查一下你的mysql服务是不是宕机了

**Comment by fly5756** [comment]
正常啊，本地安装的啊，卡着就不动了

**Comment by fly5756** [comment]
光标一直在那里闪，然后1-2分钟后就报上面的内容了

**Comment by leeqvip** [comment]
根据报错来看，不应是代码的问题
检查一下数据库配置
尝试用别的软件连接是否正常
